extend type Query {
  me: User
  user(id: ID!): User
  users: [User]
}

extend type Mutation {
  createUser(value: UserInput!): CreateUserResponse
  updateUser(id: ID!, value: UserInput!): Boolean
  deleteUser(id: ID!): Boolean
  changePassword(oldPassword: String!, newPassword: String!): Boolean
}

type User {
  id: ID
  username: String
  role: String
}

input UserInput {
  username: String
}

type CreateUserResponse {
  id: ID
  password: String
}
